
CREATE DATABASE UNIXS
GO

CREATE TABLE GES_DISCIPLINA (	-- GESTÃO DAS DISCIPLINAS
	ID_DISC INT IDENTITY(1,1) NOT NULL,
	DESC_DISC VARCHAR(100),

	CONSTRAINT PK_GES_DISCIPLINA PRIMARY KEY (ID_DISC)
	);
GO

CREATE TABLE GES_FUNCOES (
	ID_FUNCAO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DESC_FUNC VARCHAR(100) NOT NULL
	);
GO

CREATE TABLE GES_PESSOA ( -- GESTÃO DE PESSOAS (PROFESSORES, REVISORES, COORDENADORES)
	ID_PESSOA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME_PESSOA VARCHAR(100)
	);
GO

CREATE TABLE GES_PROFISSIONAIS (
	ID_PESSOA INT NOT NULL,
	ID_FUNCAO INT NOT NULL,

	CONSTRAINT FK_GES_PROFISSIONAIS_GES_PESSOA_ID_PESSOA FOREIGN KEY (ID_PESSOA)
	REFERENCES GES_PESSOA (ID_PESSOA),
	CONSTRAINT FK_GES_PROFISSIONAIS_GES_FUNCOES_ID_FUNCAO FOREIGN KEY (ID_FUNCAO)
	REFERENCES GES_FUNCOES (ID_FUNCAO)
	);
GO

CREATE TABLE GES_AULAS ( -- VINCULA PROFESSORES E AS AULAS QUE CADA UM PODE GERAR QUESTÕES
	ID_DISC INT NOT NULL,
	ID_PROF INT NOT NULL

	CONSTRAINT FK_GES_AULAS_GES_PESSOA_ID_DISC FOREIGN KEY (ID_DISC)
	REFERENCES GES_DISCIPLINA (ID_DISC),
	CONSTRAINT FK_GES_AULAS_GES_PESSOA_ID_PESSOA FOREIGN KEY (ID_PROF)
	REFERENCES GES_PESSOA (ID_PESSOA)
	);
GO

CREATE TABLE GES_QUESTOES ( -- GESTÃO DAS QUESTÕES

	ID_QUEST	INT IDENTITY(1,1) NOT NULL,
	ID_DISC		INT NOT NULL,
	DIFIC		INT NOT NULL, -- 1(FÁCIL) 2(MÉDIO) 3(DIFICIL)
	SEMANA		INT NOT NULL, -- ORDEM DE SEMANAS DO EAD	
	IS_CONS		BINARY NOT NULL, -- COM OU SEM CONSULTA
	TIPO_QUEST	BINARY NOT NULL, -- (0)OBJETIVA/(1)DISCERTATIVA
	ENUN		VARCHAR(MAX) NOT NULL,
	IS_ATIVA	INT NOT NULL, -- 1(PENDENTE) 2(ATIVA) 3(DESATIVADA)
	US0			INT NOT NULL, -- X VEZES UTILIZADA EM PROVAS

	CONSTRAINT FK_GES_QUESTOES_GES_DISCIPLINA_ID_DISC FOREIGN KEY (ID_DISC)
	REFERENCES GES_DISCIPLINA (ID_DISC),
	CONSTRAINT DIFIC CHECK (DIFIC > 0 AND DIFIC < 4),
	CONSTRAINT IS_ATIVA CHECK (IS_ATIVA > 0 AND IS_ATIVA < 4),
	CONSTRAINT PK_GES_QUESTOES PRIMARY KEY (ID_QUEST, ID_DISC, IS_CONS, TIPO_QUEST)
	); 
GO	
	
CREATE TABLE LOG_QUESTOES ( -- LOG DE EVENTO
	ID_QUEST	INT NOT NULL,
	DT_EVENTO	DATETIME NOT NULL,
	DESC_EVENTO VARCHAR(30) NOT NULL, -- CRIADA, REVISADA, APAGADA
	ID_PROF		INT NOT NULL,
	
	CONSTRAINT DESC_EVENTO CHECK (DESC_EVENTO IN ('CRIAÇÃO','REVISÃO','DELEÇÃO')),
	CONSTRAINT FK_LOG_QUESTOES_GES_PESSOA_ID_PESSOA FOREIGN KEY (ID_PROF)
	REFERENCES GES_PESSOA (ID_PESSOA),
	CONSTRAINT PK_LOG_QUESTOES PRIMARY KEY 
	(ID_QUEST, DT_EVENTO, DESC_EVENTO)
	);
GO